# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xerpE1KPR-f7Zsl5-uQTN3nlp5RDFDfT
"""

import streamlit as st
from transformers import pipeline

# Load pre-trained DistilBERT model
model = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

# Define prediction function
def predict_sentiment(text):
    result = model(text)[0]
    return result["label"], result["score"]

# Create Streamlit app
st.title("Sentiment Analysis App")
text_input = st.text_input("Enter some text")
if text_input:
    sentiment, score = predict_sentiment(text_input)
    st.write(f"Sentiment: {sentiment}, Score: {score}")
